# Generated by Django 4.2.7 on 2023-11-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
    ]
